version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docs"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/updater"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
