packages:
  - docs

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  undici@>=7.0.0 <7.29.1: ^7.29.1
  undici@>=7.1.0 <7.29.1: ^8.0.0
  undici@>=7.11.0 <7.29.1: ^7.29.1
  undici@>=7.15.0 <7.29.1: ^7.29.1
  undici@>=7.24.1 <7.29.1: ^8.0.0
  undici@>=7.28.0 <7.29.1: ^8.0.0
